"""Policy-driven synthetic data generator for end-of-turn detection.

Turns the frozen human policy (POLICY.md, data/gold_set.json) into a large
labeled training set. Pure code, seeded, reproducible; no LLM calls, so the
dataset can be regenerated byte-identically and audited line by line.

Design notes that matter:
- Every judgment-class rule from the calibration session is encoded here
  (H announced-continuation, J retraction, K self-retrieval vs narrated
  interruption). Settling hedges are deliberately NOT generated: the labeler
  put them at the boundary, so the model should learn them from nothing
  rather than from invented certainty.
- Truncation augmentation: complete utterances are also emitted cut mid-way
  and labeled wait, matching how ASR partials actually arrive.
- Every sample is emitted in a clean variant and an ASR-style variant
  (lowercased, terminal punctuation stripped) so the model cannot lean on
  punctuation as a crutch.
- Nothing here may collide with the frozen gold set; exact-text collisions
  are dropped at the end.
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

CITIES = ["Fontana", "Barstow", "Phoenix", "Denver", "Reno", "Ontario", "Stockton", "Laredo", "Memphis", "Dallas", "Atlanta", "Fresno"]
FACILITIES = ["the warehouse", "the receiver", "the shipper", "the yard", "dock four", "the cross-dock"]
LOADS = ["four seven two", "eight one five", "two two nine", "six four zero", "nine one three"]
RATES = ["eighteen fifty", "nineteen hundred", "twenty one fifty", "two thousand two hundred"]
TIMES = ["eight am", "noon", "three thirty", "six pm", "tomorrow morning", "Thursday morning"]
EQUIP = ["the reefer", "the dry van", "the flatbed", "trailer six two"]
DOCS = ["the BOL", "the rate con", "the lumper receipt", "the PO number"]
HIGHWAYS = ["the ten", "the fifteen", "the forty", "the five"]
DIGITS = ["seven one five", "four one five, five five", "three three zero, two", "six two, eight eight"]
FILLERS = ["um", "uh", "like", "you know", "I mean"]

AGENT_CTX = {
    "greet": ["Agent: Dispatch, how can I help?", "Agent: This is dispatch, go ahead."],
    "anything_else": ["Agent: Anything else I can help with?", "Agent: Is there anything else?"],
    "rate": ["Agent: Rate is {rate} all in.", "Agent: Best I can do is {rate}."],
    "ask_mc": ["Agent: Can I get your MC number?", "Agent: What is your MC?"],
    "ask_phone": ["Agent: Best callback number?", "Agent: What number can I reach you at?"],
    "ask_where": ["Agent: Where are you now?", "Agent: What is your current location?"],
    "ask_appt": ["Agent: Can you make the {time} appointment?", "Agent: Does the {time} slot work?"],
    "info": ["Agent: The dock closes at {time} today.", "Agent: Your check call is set for {time}.", "Agent: I will email you the updated BOL."],
}


def fill(t: str, rng: random.Random) -> str:
    return t.format(
        city=rng.choice(CITIES), facility=rng.choice(FACILITIES), load=rng.choice(LOADS),
        rate=rng.choice(RATES), time=rng.choice(TIMES), equip=rng.choice(EQUIP),
        doc=rng.choice(DOCS), hwy=rng.choice(HIGHWAYS), digits=rng.choice(DIGITS),
        f1=rng.choice(FILLERS), f2=rng.choice(FILLERS),
    )


def ctx(kind: str | None, rng: random.Random) -> str:
    if kind is None:
        return ""
    return fill(rng.choice(AGENT_CTX[kind]), rng)


# Each entry: (class, label, context_kind or None, list of templates)
BANKS: list[tuple[str, str, str | None, list[str]]] = [
    # A: complete statements -> speak
    ("A", "speak", "greet", [
        "I'm calling to confirm the pickup for load {load} {time}.",
        "I just dropped {equip} at the {city} yard.",
        "I'm loaded and rolling out of {city} now.",
        "The {equip} is running fine and I'm on schedule.",
        "I picked up the load from {facility} this morning.",
        "My truck is empty and I'm looking for a load out of {city}.",
    ]),
    ("A", "speak", None, [
        "I delivered to {facility} about an hour ago.",
        "The temperature on {equip} is holding steady.",
        "I already sent {doc} to your email.",
        "The receiver signed everything and I'm out of there.",
    ]),
    # B: complete questions -> speak
    ("B", "speak", None, [
        "What time does {facility} close?",
        "Can you send me {doc} again?",
        "Is detention covered after two hours at the dock?",
        "How far is {facility} from {city}?",
        "Do I need a lumper receipt for this one?",
        "What's the rate on that load out of {city}?",
        "Who do I call when I get to {facility}?",
        "Can I pick up early if I get there before {time}?",
    ]),
    # C: backchannel acks -> speak
    ("C", "speak", "info", [
        "Okay, got it.", "Sounds good.", "Perfect, thanks.", "Alright.",
        "Yeah, that works.", "Copy that.", "Okay, understood.", "Great, thank you.",
    ]),
    # D: mid-clause cutoffs -> wait
    ("D", "wait", None, [
        "I'm about twenty miles out but the traffic on {hwy} is",
        "Can you tell {facility} that my ETA is now",
        "The main problem with that lane is the",
        "So after I deliver in {city} I was planning to",
        "The broker on that load said the",
        "If the dock is backed up I might have to",
    ]),
    # E: disfluent trails -> wait
    ("E", "wait", None, [
        "Yeah so, {f1}, the thing is, {f2}",
        "I wanted to ask about, {f1},",
        "Okay so basically, {f1}, I",
        "Well, {f1}, it's kind of, {f2}",
        "So, {f1}, about the delivery, {f2}",
    ]),
    # F: mid-data pauses -> wait
    ("F", "wait", "ask_mc", [
        "Yeah, it's {digits}", "Sure, MC {digits}", "It's {digits}, hold on",
    ]),
    ("F", "wait", "ask_phone", [
        "You can reach me at {digits}", "It's {digits}", "My cell is {digits}",
    ]),
    # G: connector-final -> wait
    ("G", "wait", None, [
        "I can pick up {time}, but",
        "The rate works for me, although",
        "I'd normally take that load, except",
        "We can do the drop trailer, and",
        "I can be there by {time}, so",
    ]),
    # H: complete-then-maybe-more -> speak (policy: respond, barge-in covers the miss)
    ("H", "speak", "ask_where", ["Just passed {city}.", "About an hour out of {city}.", "Sitting at {facility} right now."]),
    ("H", "speak", "ask_appt", ["Yeah, I can make it.", "That works for me.", "Yes, no problem."]),
    ("H", "speak", "rate", ["That rate works for me.", "Okay, I'll take it.", "Deal, book it."]),
    ("H", "speak", None, [
        "I'll call {facility} myself.",
        "Send the paperwork to my email.",
        "I delivered the load about an hour ago.",
        "Okay, I'll head there now.",
    ]),
    # H exception: announced continuation -> wait
    ("H", "wait", "anything_else", [
        "Actually yeah, one more thing.",
        "Oh wait, there's something else.",
        "Before I forget, one more question.",
        "Hold on, one other thing.",
    ]),
    # I: handoff hedges -> speak (policy: hedges are handoffs; settling hedges stay out of training)
    ("I", "speak", None, [
        "That's all I need, I guess.",
        "That covers everything, I think.",
        "I'll take the {city} load, I suppose.",
        "We should be all set then, I guess.",
    ]),
    # I hedge ruling: genuinely-unsure stance (reported speech, real doubt) invites confirmation -> speak
    ("I", "speak", None, [
        "The broker said the lumper was covered, supposedly.",
        "They told me the dock opens at {time}, apparently.",
        "Dispatch said the rate got bumped to {rate}, supposedly.",
        "The shipper told me it's a drop trailer, I think.",
    ]),
    # I hedge ruling: sure stance with a decorative softener, mid-narrative statement -> wait
    ("I", "wait", None, [
        "The detention was approved, or something",
        "The appointment moved to {time}, or whatever",
        "The rate came out to {rate}, or something like that",
        "The trailer got swapped at {facility}, or whatever it was",
    ]),
    ("I", "speak", None, [
        "They said the gate code is the same as last time, supposedly.",
        "The receiver told me I can come early, apparently.",
        "My dispatcher said you'd have the rate con already, I think.",
        "That should be everything on my end, I guess.",
    ]),
    ("I", "wait", None, [
        "The gate code changed last week, or something",
        "The lumper fee was ninety bucks, or whatever",
        "The pallet count came out to twenty two, or something like that",
    ]),
    ("K", "wait", None, [
        "Hold on, I'm scrolling to find it",
        "Wait, it's in my other email, one sec",
        "Let me pull the rate con up on my phone",
        "Hang on, I'm looking for the gate code",
    ]),
    ("K", "speak", None, [
        "The dock guy is calling me over, hang on",
        "I'm getting flagged through the gate, one second",
        "My co-driver is asking me something, hold on",
    ]),
    ("A", "speak", None, [
        "I need to move my dentist appointment to Thursday.",
        "The package finally showed up this morning.",
        "I'm heading to the gym right after this call.",
    ]),
    ("B", "speak", None, [
        "What's the weather looking like this weekend?",
        "How long is the drive to the airport at five?",
        "Did anything important come in this morning?",
    ]),
    ("D", "wait", None, [
        "Can you add a reminder for the thing about the",
        "I was going to ask you about the email from",
    ]),
    # J: self-interrupt restarts -> wait
    ("J", "wait", None, [
        "Book me on the- wait, hold on",
        "I need the- no, hang on",
        "Tell them I'll be- hmm, let me rethink this",
        "The pickup is at- sorry, I'm reading the wrong load",
        "Set my check call for- actually",
        "My ETA is- ugh, this GPS just rerouted",
    ]),
    # J exception: full retraction -> speak
    ("J", "speak", None, [
        "Can you check the- no, scratch that.",
        "Send me the- never mind, I found it.",
        "Book the- forget it, I'll do it online.",
    ]),
    # K: self-retrieval hold -> wait
    ("K", "wait", None, [
        "Hang on, let me grab the load number",
        "One sec, let me check {doc}",
        "Let me find {doc} real quick",
        "Give me a second to pull up the load",
        "Uh, let me look at my calendar",
        "Wait, let me read the confirmation email",
    ]),
    # K: narrated external interruption -> speak (a brief courtesy ack is a response)
    ("K", "speak", None, [
        "Hold on, I'm pulling over so I can read it",
        "One sec, the receiver is waving at me",
        "Let me ask my dispatcher and get back to you",
        "I've got another call coming in, hang on",
        "Someone's at my window, give me a minute",
    ]),
]


def asr_variant(text: str) -> str:
    t = text.lower().rstrip()
    while t and t[-1] in ".?!":
        t = t[:-1].rstrip()
    return t


def truncate(text: str, rng: random.Random) -> str | None:
    words = text.rstrip(".?!").split()
    if len(words) < 5:
        return None
    cut = rng.randint(max(2, int(len(words) * 0.4)), len(words) - 2)
    return " ".join(words[:cut])


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="data/train.jsonl")
    ap.add_argument("--per-template", type=int, default=10, help="filled instances per template")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--gold", default="data/gold_set.json")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    rows: list[dict] = []

    for cls, label, ctx_kind, templates in BANKS:
        for t in templates:
            for _ in range(args.per_template):
                text = fill(t, rng)
                context = ctx(ctx_kind, rng)
                rows.append({"context": context, "text": text, "label": label, "cls": cls, "variant": "clean"})

    # Truncation augmentation: complete speak utterances re-emitted cut short, labeled wait.
    speak_rows = [r for r in rows if r["label"] == "speak" and r["cls"] in ("A", "B", "H")]
    for r in speak_rows:
        cut = truncate(r["text"], rng)
        if cut:
            rows.append({"context": r["context"], "text": cut, "label": "wait", "cls": "T", "variant": "clean"})

    # ASR-style variant of everything: lowercase, no terminal punctuation.
    for r in list(rows):
        t = asr_variant(r["text"])
        if t != r["text"]:
            rows.append({**r, "text": t, "variant": "asr"})

    # Dedup and drop any exact-text collision with the frozen gold set.
    gold = json.load(open(args.gold))
    gold_texts = {s["text"].strip().lower() for s in gold["samples"]}
    seen: set[tuple[str, str]] = set()
    out: list[dict] = []
    for r in rows:
        key = (r["context"], r["text"])
        if key in seen or r["text"].strip().lower() in gold_texts:
            continue
        seen.add(key)
        out.append(r)
    rng.shuffle(out)

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w") as f:
        for r in out:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    from collections import Counter
    by_label = Counter(r["label"] for r in out)
    by_cls = Counter(r["cls"] for r in out)
    print(f"wrote {len(out)} samples to {args.out}")
    print("labels:", dict(by_label))
    print("classes:", dict(sorted(by_cls.items())))


if __name__ == "__main__":
    main()
